version: '3'
services:
  app:
    container_name: docker_ node_group1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - docker-network
    volumes:
      - docker-vol:/app
    environment:
      - PORT=3000
    DATABASE_URL: ''

volumes:
  docker-vol:

networks:
  docker-network:
  
  